=== edouard-capdepon/ProjetXML/src/xml/Menu.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalogue">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="menu" type="typeMenu" maxOccurs="unbounded"/>
                <xs:element name="boissons">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="boisson" type="typeBoisson" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="moyenPaiement" maxOccurs="unbounded" >
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Carte Bancaire"></xs:enumeration>
                            <xs:enumeration value="Espece"></xs:enumeration>
                            <xs:enumeration value="Paypal"></xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Type Menu -->
    <xs:complexType name="typeMenu">
        <xs:sequence>
            <xs:element name="entree" type="typeEntree" maxOccurs="unbounded"/>
            <xs:element name="plat" type="typeChild"/>
            <xs:element name="fromage" type="typeChild" minOccurs="0"/>
            <xs:element name="dessert" type="typeChild" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="boisson" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="incluse au choix"/>
                    <xs:enumeration value="non-incluse"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="prix" type="xs:double" use="required"/>
    </xs:complexType>

    <!-- Type Entree -->
    <xs:complexType name="typeEntree">
        <xs:complexContent>
            <xs:extension base="typeChild">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="froide"/>
                            <xs:enumeration value="chaude"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- Type Child -->
    <xs:complexType name="typeChild">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Type Boisson -->
    <xs:complexType name="typeBoisson">
        <xs:sequence>
            <xs:element name="nom">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Coca Cola"/>
                        <xs:enumeration value="Fanta"/>
                        <xs:enumeration value="Eau Plate"/>
                        <xs:enumeration value="Eau Gazeuse"/>
                        <xs:enumeration value="Coca Cherry"/>
                        <xs:enumeration value="Vin"/>
                        <xs:enumeration value="Rosé"/>
                        <xs:enumeration value="Bierre"/>
                        <xs:enumeration value="Café"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="prix" type="xs:double" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== edouard-capdepon/ProjetXML/src/xml/Menu.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<?xml-stylesheet type="text/xsl" href="Menu.xsl"?>
<catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Menu.xsd">

    <menu boisson="incluse au choix" prix="17.5">
        <entree>
            <nom>TESTNOM</nom>
            <description>TESTDESCRIPTION</description>
        </entree>
        <plat>
            <nom>TESTNOM</nom>
            <description>TESTDESCRIPTION</description>
        </plat>
        <fromage>
            <nom>TESTNOM</nom>
            <description>TESTDESCRIPTION</description>
        </fromage>
        <dessert>
            <nom>TESTNOM</nom>
            <description>TESTDESCRIPTION</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="20">
        <entree type="froide">
            <nom>Tartare de saumon</nom>
            <description>un tartare de saumon est un plat de la cuisine française, reprenant le principe du steak
                tartare, mais en l'appliquant au saumon.
            </description>
        </entree>
        <plat>
            <nom>Blanquette de veau facile</nom>
            <description>un plat traditionnel, la blanquette de veau, version Hervé Cuisine, qui se traduit par une
                viande fondante et une sauce onctueuse
            </description>
        </plat>
        <fromage>
            <nom>Le Bleu d'Auvergne</nom>
            <description>un fromage français de lait de vache du Massif central.</description>
        </fromage>
        <dessert>
            <nom>Crème brulée</nom>
            <description>un dessert composé de jaunes d'œufs, de sucre, de crème, de vanille et de caramel</description>
        </dessert>
        <dessert>
            <nom>Choux crème et citron vert</nom>
            <description>un dessert composé de choux à la crème de citron vert</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="15">
        <entree type="chaude">
            <nom>Soupe vitaminée</nom>
            <description>une soupe composée de carotte, orange et panais</description>
        </entree>
        <plat>
            <nom>Lasagnes à la bolognaise</nom>
            <description>une des spécialités italiennes</description>
        </plat>
        <dessert>
            <nom>Flan parisien</nom>
            <description>un flan sur une base de pâte brisée</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="15">
        <entree type="froide">
            <nom>Salade de crevettes au curry</nom>
            <description>une salade à base de crevettes et une sauce de cuzzy</description>
        </entree>
        <plat>
            <nom>Sauté de veau au chorizo</nom>
            <description>une recette portugaise</description>
        </plat>
        <dessert>
            <nom>Oeufs à la neige crème à la vanille</nom>
            <description>un dessert composé de lait, ouefs, et sucre</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="12.5">
        <entree>
            <nom>entree1</nom>
            <description>Description 1 de l'entree 1</description>
        </entree>
        <plat>
            <nom>Plat1</nom>
            <description>Description 1 du plat 1</description>
        </plat>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="12.5">
        <entree>
            <nom>entree1</nom>
            <description>Description 1 de l'entree 1</description>
        </entree>
        <entree>
            <nom>entree1</nom>
            <description>Description 1 de l'entree 1</description>
        </entree>
        <plat>
            <nom>Plat1</nom>
            <description>Description 1 du plat 1</description>
        </plat>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="12.5">
        <entree>
            <nom>entree1</nom>
            <description>Description 1 de l'entree 1</description>
        </entree>
        <plat>
            <nom>Plat1</nom>
            <description>Description 1 du plat 1</description>
        </plat>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
    </menu>
    <menu boisson="non-incluse" prix="12.5">
        <entree>
            <nom>entree2</nom>
            <description>Description 1 de l'entree 2</description>
        </entree>
        <plat>
            <nom>Plat2</nom>
            <description>Description 1 du plat 2</description>
        </plat>
        <fromage>
            <nom>Fromage1</nom>
            <description>Description 1 du fromage 1</description>
        </fromage>
        <dessert>
            <nom>Dessert2</nom>
            <description>Description 1 du dessert2</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="12.5">
        <entree>
            <nom>entree1</nom>
            <description>Description 1 de l'entree 1</description>
        </entree>
        <plat>
            <nom>Plat1</nom>
            <description>Description 1 du plat 1</description>
        </plat>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
    </menu>
    <menu boisson="non-incluse" prix="12.5">
        <entree>
            <nom>entree2</nom>
            <description>Description 1 de l'entree 2</description>
        </entree>
        <plat>
            <nom>Plat2</nom>
            <description>Description 1 du plat 2</description>
        </plat>
        <fromage>
            <nom>Fromage1</nom>
            <description>Description 1 du fromage 1</description>
        </fromage>
        <dessert>
            <nom>Dessert2</nom>
            <description>Description 1 du dessert2</description>
        </dessert>
    </menu>
    <menu boisson="incluse au choix" prix="12.5">
        <entree>
            <nom>entree1</nom>
            <description>Description 1 de l'entree 1</description>
        </entree>
        <plat>
            <nom>Plat1</nom>
            <description>Description 1 du plat 1</description>
        </plat>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
        <dessert>
            <nom>Dessert1</nom>
            <description>Description 1 du dessert1</description>
        </dessert>
    </menu>
    <boissons>
        <boisson prix="1">
            <nom>Eau Plate</nom>
        </boisson>
        <boisson prix="1.5">
            <nom>Eau Gazeuse</nom>
        </boisson>
        <boisson prix="2.5">
            <nom>Coca Cola</nom>
        </boisson>
        <boisson prix="1">
            <nom>Café</nom>
        </boisson>
    </boissons>

    <moyenPaiement>Carte Bancaire</moyenPaiement>
    <moyenPaiement>Paypal</moyenPaiement>
    <moyenPaiement>Espece</moyenPaiement>

</catalogue>
